# -*- coding: utf-8 -*-
"""function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qE14vUFW_w0Jn1ktX-4z9E_brJPtLIEX
"""

# def greeting(nama_orang,alamat):
#   print("hallo! Selamat Pagi",nama_orang,"🙏😊")
#   print("kamu orang lingkungan :",alamat)

# greeting("sigit","muara gembong")
# greeting("akbar","bekasi")
# greeting("kenzi","cikarang")

# data_kelas = []

# def view():
#   print("data kelas:")
#   if len(data_kelas) == 0:
#     print("datanya kosong")
#   else:
#     for i in data_kelas:
#       print(i)

# def average(nama,a,b,c,d,e):
#   global avg
#   avg = (a+b+c+d+e)/5
#   print("nilai rata-rata",nama,":",avg)
#   return avg

# # average("raffi",60,92,93,70,40)
# # print(avg)
# # view()

# view()
# data_kelas.append(average("raffi",90,92,93,98,87))
# data_kelas.append(average("alifa",98,90.2,93,95,97))
# view()
# average("alifa",98,90.2,93,95,97)
# data_kelas.append(avg)
# print(avg)


# average("raffi",60,92,93,70,40) = 71.0


# def nilai(a):
#   global tambah
#   tambah =a+a
#   return tambah

# nilai(6)
# print("hasil print tambah:",tambah)

# print("hasil return dari function:", nilai(5))



count = 0

def increment():
  global count
  count += 1
  return count

print("count awal:",count)
increment()
print("count setelah:",increment())

