# -*- coding: utf-8 -*-
"""List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JgHFdwxXzW7ho5vauOUHjuJdtryhYWT-
"""

# name = "alifia"
# print(len(name))
# print("ini adalah indeks ke-2:",data[2])
# print(data[0])
# print(data[1])
# print(data[2])
# print(data[3])
# print(data[4])

# while True:
#     print("lihat menu:\n1.view\n2.exit\n")
#     pertanyaan = int(input("masukan pilihan kamu:"))

#     if pertanyaan == 1:
#         for i in data:
#           print(i)
#           break
#     else:
#         print("berhenti")
#         break

# angka1 = int(input("masukan angka kesatu:"))
# angka2 = int(input("masukan angka kedua:"))

# print(angka1)
# print(angka2)
# print(angka1*angka2)



data = [50,2,30,4,5]
print("data:")
nomor = 1
for i in data:
  print(nomor,".",i)
  nomor += 1
# menambahkan sesuatu (append)
# bb = int(input("masukan bb:"))
# data.append(bb)

# edit nilai:
nomor_ubah = int(input("masukan urutan yang mau diubah:"))
VALUE_ubah = int(input("masukan urutan yang mau diubah:"))

# data[1] = 8
data[nomor_ubah] = VALUE_ubah

# menghapus sesuatu(remove, pop)
# kalo remove berdasarkan nilainya
# data.remove(50)
# kalo pop berdasarkan indeksnya
# data.pop(0)

print("data setelah diubah:")
for i in data:
  print(i)