# -*- coding: utf-8 -*-
"""operator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VVA28d5WMt-7wV79pp2982w_M0pCdGC6
"""

import random
# library untuk fitur random (int, float(uniform))

# operator assignment : +=,-=,/=,*=
uang = 0
mama = 1000000
uang += mama
print("uang saya sekarang:",uang)


adek = 550000
uang -= adek
print("uang saya sekarang:",uang)

# saham = 0.02
# jika pake random :
saham = random.uniform(0,1)
print(saham)
keuntungan = uang * saham
# # uang *= saham
print("keuntungan:",keuntungan)
uang += keuntungan
print("uang saya sekarang:",uang)

# # # operator relasional
# # a = 5
# # b = "5"
# # print(a==b)
# # uang = str(uang)
if uang>800000:
  print("kamu boleh jajan")
elif uang >= 500000:
  print("kamu gaboleh jajan harus kerja")
else:
  print("tak terdeteksi")

# contoh modulo:
# print(91%7)